version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: 
        name: Wait for DB
        command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
